shared: &shared
  adapter: mysql2
  reconnect: true
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password:

development:
  database: share_videos
  <<: *shared

test: &TEST
  database: share_videos
  <<: *shared
